S02US16
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-Externatic pull request #1
Opened 2023-12-19 14:58 UTC by Chikoulat

Feat: Database structure done.

2023-12-19 15:09 UTC, YOUNS28100 approved these changes

2023-12-19 15:14 UTC, sdiakhate approved these changes

2023-12-20 14:08 UTC, ioayoub requested changes
❌ - As discussed, empty files are not allowed

2023-12-21 10:04 UTC, ioayoub approved these changes

2023-12-21 13:43 UTC, StalkerVince approved these changes
Approuvé!

2023-12-21 13:51 UTC, merged