S05US02 Inscription Candidat/Entreprise + liaison DB
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-Externatic pull request #21
Opened 2024-01-25 10:59 UTC by StalkerVince

2024-01-25 11:30 UTC, Chikoulat commented on frontend/src/pages/SignUp.jsx
> +      <header>
pas besoin de garder le header.

2024-01-25 11:30 UTC, Chikoulat commented on frontend/src/pages/SignUp.jsx
> +      <footer>
Pas besoin de garder le footer.

2024-01-25 11:31 UTC, Chikoulat requested changes
Supprime ton header et footer stp

2024-01-25 17:44 UTC, Chikoulat approved these changes

2024-01-25 23:51 UTC, sdiakhate approved these changes

2024-01-26 08:04 UTC, ioayoub approved these changes

2024-01-26 08:17 UTC, closed without merging