S05US08fix
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-Externatic pull request #26
Opened 2024-01-30 17:21 UTC by Chikoulat

FIX: Fixed bugs.
UPDATE: Updated login CSS and made it responsive.
FEATURE: Added externaticData for database.

2024-02-01 17:18 UTC, ioayoub requested changes

2024-02-01 17:18 UTC, ioayoub commented on backend/src/app.js
> +// const reactBuildPath = `${__dirname}/../../frontend/dist`;
Please clean this file

2024-02-01 17:18 UTC, ioayoub commented on backend/src/services/upload.js
> +/* const multer = require("multer");
Please clean this file

2024-02-05 09:38 UTC, ioayoub approved these changes

2024-02-05 09:40 UTC, YOUNS28100 approved these changes

2024-02-05 09:49 UTC, StalkerVince approved these changes

2024-02-05 10:06 UTC, merged