S02 us21
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-Externatic pull request #4
Opened 2023-12-21 14:46 UTC by YOUNS28100

2023-12-21 14:48 UTC, Chikoulat approved these changes

2023-12-21 14:49 UTC, sdiakhate approved these changes

2023-12-21 20:09 UTC, ioayoub requested changes

2023-12-21 20:09 UTC, ioayoub commented on backend/src/controllers/userController.js
> +  //   read,
Remove this if not used

2023-12-21 21:15 UTC, YOUNS28100 commented on backend/src/controllers/userController.js
> +  //   read,
Fixed, thank you for your feedback

2023-12-22 08:23 UTC, ioayoub approved these changes

2023-12-22 08:30 UTC, StalkerVince approved these changes

2023-12-22 08:39 UTC, merged